### ISSUE TITLE
Placement in settings

### ISSUE THREAD

**Issue by sam411** [EmranAhmed/woo-cart-redirect-to-checkout-page#1]
Hi, 

I suggest changing 
		
#97 array_splice( $settings, 6, 0, array(
to
#97 array_splice( $settings, **5**, 0, array(

as the 6 places the settings in my woocommerce underneath the 'Measurements' sections, which confused me at first.

Good plugin, thank you.
SAMUEL

**Comment by EmranAhmed** [comment]
Hay sam,

Nobody care about this little plugin but you did and gave your suggestion, Thank you buddy 👍
